pipeline:
  setup:
    image: docker:git
    commands:
      - git clone --depth 1 https://github.com/annot8/annot8-common.git annot8-common
      - git clone --depth 1 https://github.com/annot8/annot8-components.git annot8-components
      - git clone --depth 1 https://github.com/annot8/annot8-conventions.git annot8-conventions
      - git clone --depth 1 https://github.com/annot8/annot8-core.git annot8-core
      - git clone --depth 1 https://github.com/annot8/annot8-default-impl.git annot8-default-impl
      - git clone --depth 1 https://github.com/annot8/annot8-parent.git annot8-parent
      - git clone --depth 1 https://github.com/annot8/annot8-testing.git annot8-testing
  build:
    image: maven:3-jdk-10
    commands:
      - mvn -B clean test
